%% generated by soap from: /home/yogesh/Desktop1/sem6/cc/assignments/group-assign/calculator/src/calculator
%% for service "Calculator" and port "CalculatorSoap"
%% using options: [{service,"Calculator"},{port,"CalculatorSoap"},{generate,both},{namespaces,[{"http://example.com/calculator.xsd","P0"}]},{generate_tests,both},{http_server,soap_server_cowboy_2},{server_name,"calculator_server"},{http_client,soap_client_ibrowse},{client_name,"calculator_client"},{strict,true}]

-module(calculator_client_stub).

-include("calculator.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export([add/3]).
-export([subtract/3]).
-export([multiply/3]).
-export([divide/3]).

-spec add(Soap_body::'P0:Add'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:AddResponse'()).
add(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"add\"", interface()).

-spec subtract(Soap_body::'P0:Subtract'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:SubtractResponse'()).
subtract(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"subtract\"", interface()).

-spec multiply(Soap_body::'P0:Multiply'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:MultiplyResponse'()).
multiply(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"multiply\"", interface()).

-spec divide(Soap_body::'P0:Divide'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:DivideResponse'()).
divide(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"divide\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.